### ISSUE TITLE
Missing API_BASE leads to IOError when hitting /

### ISSUE THREAD

**Issue by adborden** [eregs/regulations-site#140]
https://gist.github.com/anonymous/19bd2386b12c1f416b92

README should include how to set the API_BASE so regulations-site knows where to get data from. We can use atf-eregs as an example.

```
$ echo "API_BASE = 'https://atf-eregs.apps.cloud.gov/api/'" >> local_settings.py
```

**Comment by cmc333333** [comment]
This was added #489
